#!/bin/bash

# Usage
# bucketsync ACCESSKEY SECRETKEY SYNCDIR BUCKETNAME

# Usage example
# bucketsync AK1234556 DFEWAefwj381012 ./public/ sample-bucket
configfile=.tmp_s3cfg
ignorefile=.tmp_s3ignore

cat << EOT >> $configfile
[default]
access_key = $1
bucket_location = ap-northeast-1
cloudfront_host = cloudfront.amazonaws.com
cloudfront_resource = /2010-07-15/distribution
default_mime_type = binary/octet-stream
delete_removed = False
dry_run = False
encoding = UTF-8
encrypt = False
follow_symlinks = False
force = False
get_continue = False
gpg_command = None
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = 
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
list_md5 = False
log_target_prefix = 
preserve_attrs = True
progress_meter = True
proxy_host = 
proxy_port = 0
recursive = False
recv_chunk = 4096
reduced_redundancy = False
secret_key = $2
send_chunk = 4096
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
urlencoding_mode = normal
use_https = True
verbosity = WARNING
EOT

cat << EOT >> $ignorefile
$configfile
$ignorefile
bucketsync
.DS_Store
.git
.git/*
EOT

s3cmd sync --guess-mime-type --delete-removed --add-header=Cache-Control:no-cache $3 -P --follow-symlinks --config $configfile --exclude-from $ignorefile s3://$4
rm $configfile
rm $ignorefile
